package com.cake.server.dao;

import com.cake.server.entity.Example;
import com.cake.server.entity.ExampleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExampleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table example
     *
     * @mbg.generated Mon Apr 02 15:44:57 CST 2018
     */
    long countByExample(ExampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table example
     *
     * @mbg.generated Mon Apr 02 15:44:57 CST 2018
     */
    int deleteByExample(ExampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table example
     *
     * @mbg.generated Mon Apr 02 15:44:57 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table example
     *
     * @mbg.generated Mon Apr 02 15:44:57 CST 2018
     */
    int insert(Example record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table example
     *
     * @mbg.generated Mon Apr 02 15:44:57 CST 2018
     */
    int insertSelective(Example record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table example
     *
     * @mbg.generated Mon Apr 02 15:44:57 CST 2018
     */
    List<Example> selectByExample(ExampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table example
     *
     * @mbg.generated Mon Apr 02 15:44:57 CST 2018
     */
    Example selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table example
     *
     * @mbg.generated Mon Apr 02 15:44:57 CST 2018
     */
    int updateByExampleSelective(@Param("record") Example record, @Param("example") ExampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table example
     *
     * @mbg.generated Mon Apr 02 15:44:57 CST 2018
     */
    int updateByExample(@Param("record") Example record, @Param("example") ExampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table example
     *
     * @mbg.generated Mon Apr 02 15:44:57 CST 2018
     */
    int updateByPrimaryKeySelective(Example record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table example
     *
     * @mbg.generated Mon Apr 02 15:44:57 CST 2018
     */
    int updateByPrimaryKey(Example record);
}